language: ruby
bundler_args: --without development 
rvm:
  - "1.9.3"
before_script: 
  - gem install bundler rake
  - cat 2012/entries/**/Gemfile > Gemfile # yes this will break if people require inconsistent gems. Please commit some saner testing mechanism.
  - bundle install  
script: bundle exec rake test_all
